### ISSUE TITLE
Arcana Error on world load (crash to main menu)

### ISSUE THREAD

**Issue by TheEventHorizon** [Kenan2000/CDDA-Kenan-Modpack#108] opened 2021-07-04 00:12 UTC
Only mods loaded are default + arcana
![CDDA Arcana Fatigue error](https://user-images.githubusercontent.com/13070997/124369572-ce69be00-dc21-11eb-9f4b-128627ed0a85.PNG)

**Comment by Kenan2000** [comment] 2021-07-04 01:41
@TheEventHorizon Open an issue here https://github.com/chaosvolt/cdda-arcana-mod, Chaosvolt is the creator and maintainer of this mod, he updates it, he fixes it as well

**Comment by chaosvolt** [comment] 2021-07-04 01:45
You're using either an outdated version of Arcana in more recent DDA versions, or you put the BN version of Arcana into DDA instead. Basically, DDA no longer supports fatigue as a power source for spells, while BN still does.

**Comment by TheEventHorizon** [comment] 2021-07-04 03:53
@chaosvolt I did find Arcana_BN in my mods folder. I deleted it and still ran into the same issue. Where is the BN version from? I don't see it listed in this mod pack?

**Comment by TheEventHorizon** [comment] 2021-07-04 03:57
Yeah ok, wow. Upon further testing it seems 0.F just borked almost all third party mods to SOME extent, from the mildly inconvenient to not even loading a world. I'll just hang around on the more recent dev builds of 0.E for now. Awesome mod pack btw, can't play without it any more. :D

**Comment by chaosvolt** [comment] 2021-07-04 06:15
How the fuck did they do that?

**Comment by chaosvolt** [comment] 2021-07-04 06:25
Okay, I just tested this in 0.F stable. I load-tested it. I debug-learned all spells. Then for good measure I scrolled through the entire spellcasting menu. No errors.

Can't reproduce this.

**Comment by Theawesomeboophis** [comment] 2021-07-04 13:11
I managed to reproduce on experimental with regular Arcana ( Not BN version), not sure what's causing it. Almost all third party mods are slightly or majorly broken on experimental.

**Comment by chaosvolt** [comment] 2021-07-04 16:27
Are you sure you're using the right version? Make sure you actually clean out the old folder for the BN version first.

**Comment by Theawesomeboophis** [comment] 2021-07-04 16:30
> Are you sure you're using the right version? Make sure you actually clean out the old folder for the BN version first.

I've never used BN version, as I don't play BN.

**Comment by chaosvolt** [comment] 2021-07-04 16:35
Okay, this is weird. I tested this on 0.F stable and couldn't reproduce this. Then I tested this on today's experimental build and it's there. Searched through and found out the cause, an item spell I'd recently added was set to cast from fatigue and I forgot about it when porting that spell over to the DDA version.

Annoying thing is, the PR that removed that feature was merged months ago, so I don't know why it didn't report this bug until after 0.F stable. Did they only removing the code from it afterwards or something?

**Comment by Theawesomeboophis** [comment] 2021-07-04 16:37
I don't know the cause, but I could fix it if I knew which file it was from.

**Comment by chaosvolt** [comment] 2021-07-04 16:39
Should now be fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/7e96dea885697cb6b23d41dc7975d353121510f2

**Comment by Theawesomeboophis** [comment] 2021-07-04 16:40
> Should now be fixed by [chaosvolt/cdda-arcana-mod@7e96dea](https://github.com/chaosvolt/cdda-arcana-mod/commit/7e96dea885697cb6b23d41dc7975d353121510f2)

Thanks. I'll list a list of errors from other mods here and try fixing those later today as well, 0.f experimental broke a lot of mods.

**Comment by chaosvolt** [comment] 2021-07-04 16:49
Ping me if you find any in my mods, as well as any in Cata++ or Mining Mod since I'm gonna be checking on those too. There's already https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/281 it seems.

**Comment by Theawesomeboophis** [comment] 2021-07-04 16:53
Will do, I already know secronom and a few others are having issues because of burst being removed.

**Comment by linonetwo** [comment] 2021-07-06 03:18
can be closed, too, the fix has been ported to this repo.

**Comment by Theawesomeboophis** [comment] 2021-07-06 03:27
All mods are fixed already?! Kenan's fast, welp, time to reenter my
addiction to Cataclysm once again.

**Closed** 2021-07-06 11:18 UTC
