### ISSUE TITLE
CTD when butchering long string to thread

### ISSUE THREAD

**Issue by slowleakage** [Kenan2000/CDDA-Kenan-Modpack#12] opened 2021-01-06 01:59 UTC
Multiple crashes spanning the last couple versions. Repeatable by butchering long string to thread.

Debug
https://pastebin.com/CkAFTK01

Crash Log:
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-8740-g618a3be
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x6a6ba6[cataclysm-tiles.exe+0x2a6ba6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x6a6ba6),
    (libbacktrace: 0x6a6ba6    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x68145f[cataclysm-tiles.exe+0x28145f]), 
    (libbacktrace: log_crash+0x4af@0x68145f),
    (libbacktrace: 0x68145f    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x682132[cataclysm-tiles.exe+0x282132]), 
    (libbacktrace: signal_handler+0x32@0x682132),
    (libbacktrace: 0x682132    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: SMPEG_error+0x4b034@0x126abf0[cataclysm-tiles.exe+0xe6abf0]), 
    (libbacktrace: gnu_exception_handler+0x70@0x126abf0),
    (libbacktrace: 0x126abf0    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crt_handler.c:223    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffdf1fd7ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffdf2c9130f[ntdll.dll+0xa130f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ffdf2c3b5e4[ntdll.dll+0x4b5e4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffdf2c8fe3e[ntdll.dll+0x9fe3e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x91a258[cataclysm-tiles.exe+0x51a258]), 
    (libbacktrace: ZN4itemC1ERKS_+0x28@0x91a258),
    (libbacktrace: 0x91a258    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x669cf0[cataclysm-tiles.exe+0x269cf0]), 
    (libbacktrace: ZN9Character20complete_disassembleE13item_location+0xa0@0x669cf0),
    (libbacktrace: 0x669cf0    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x42a6f0[cataclysm-tiles.exe+0x2a6f0]), 
    (libbacktrace: ZN26disassemble_activity_actor6finishER15player_activityR9Character+0x90@0x42a6f0),
    (libbacktrace: 0x42a6f0    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0xed9399[cataclysm-tiles.exe+0xad9399]), 
    (libbacktrace: ZN15player_activity7do_turnER6player+0xdb9@0xed9399),
    (libbacktrace: 0xed9399    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x798788[cataclysm-tiles.exe+0x398788]), 
    (libbacktrace: ZN4game16process_activityEv+0x58@0x798788),
    (libbacktrace: 0x798788    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7e351a[cataclysm-tiles.exe+0x3e351a]), 
    (libbacktrace: ZN4game7do_turnEv+0x30a@0x7e351a),
    (libbacktrace: 0x7e351a    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: IMG_LoadWEBP_RW+0x7c2c89@0x1b1f6e9[cataclysm-tiles.exe+0x171f6e9]), 
    (libbacktrace: main+0x1239@0x1b1f6e9),
    (libbacktrace: 0x1b1f6e9    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x4013ed[cataclysm-tiles.exe+0x13ed]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013ed),
    (libbacktrace: 0x4013ed    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:336    __tmainCRTStartup),
  #16
    (dbghelp: @0x4014fb[cataclysm-tiles.exe+0x14fb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014fb),
    (libbacktrace: 0x4014fb    /home/narc/src/mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:186    WinMainCRTStartup),
  #17
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffdf1d17034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #18
    (dbghelp: RtlUserThreadStart+0x21@0x7ffdf2c3d0d1[ntdll.dll+0x4d0d1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by Kenan2000** [comment] 2021-01-06 18:39
@slowleakage Are you sure that it's the Modpack's problem in this case?Have you tried doing the same with no mods installed?

**Comment by slowleakage** [comment] 2021-01-07 00:07
I created a new world with no mods and was unable to duplicate the CTD. Butchered strings individually and recursively with no crash for two game days, about 10k thread, until being parched prevented batch butchering. No luck. 

Thanks for the amazing mod pack!

**Comment by Kenan2000** [comment] 2021-01-07 01:39
> I created a new world with no mods and was unable to duplicate the CTD. Butchered strings individually and recursively with no crash for two game days, about 10k thread, until being parched prevented batch butchering. No luck.
> 
> Thanks for the amazing mod pack!

No problem, a pleasure to work for the community, I'm glad to hear that you're enjoying the Modpack :-)
Thanks for providing more information about this bug, I will try to trace down the mod that actually causes it, right now tracing some other mods which cause a crash upon reaching `Items` during world generation, as you can see based on the most recent commits

Tons of work to do, as usually :-)

**Comment by Kenan2000** [comment] 2021-01-08 23:07
@slowleakage Just tested on latest experimental version with the mods below installed (all mods from the Modpack):

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-8821-ged07fdc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Wandering Masters [wandering_masters],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Safe Autodoc [safe_autodoc],
    Portable Autodoc [portable_autodoc],
    Manual Bionic Installation [manualbionicinstall],
    Clean CBMs [clean_cbm],
    Xeno's SAS4 weapons pack [Xeno_SAS4],
    Locked and Loaded [Locked_and_Loaded],
    <color_red>Sierra Madre</color> [sierra_madre],
    <color_light_red>Secronom</color> [secronom],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bionic Professions [package_bionic_professions],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Wild Living [WildLiving],
    Battle Maid Redux [battle_maid],
    C.R.I.T Expansion Mod [crt_expansion],
    Engineering essentials [EngineeringEssentials],
    Magiclysm [magiclysm],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Magiclysm Revamp and Additions [magicrevamp],
    Make bows great again [bow_opness],
    Nechronica Redux [Nechronica_Redux],
    Pneumatic fun [pneumo_fun],
    Mutant NPCs [mutant_npcs_new],
    Psychiclysm [psychiclysm],
    Whaleys Collectables [collectablemod],
    XEAS [XEAS],
    Add Rice [rice],
    Advanced Gear Goats Edition [adv_gear],
    Advanced Technologies [advtech],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Bens GF recipes [Tolerate_This],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Bootleg Walkers [Bootleg_Walkers],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Fallout New England [fallout],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Garden Pots [growable-pots],
    Gourmand's Graces [Gourmand'sGraces],
    Gun Cotton [guncotton],
    Homestead Instruments Inc. [homestead],
    Blazemod - Vehicle Additions Pack [blazemod],
    vorpal weapons [vorpal_weapons],
    Sarcophagi Access [sarcophagi_access],
    ProjectKawaii [ProjectKawaii],
    Nimian Manufacture Guns [NM_wpns],
    machine [machine],
    Jury-Rigged Robots [jury_rigged_robots],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Amplified @'s Features [amplified_players_features],
    Necromancy [necromancy],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Cars to Wrecks [cars_to_wrecks],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Water Towers [water_towers],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Morlock Village [morlock_village],
    More City Locations [cityside],
    Dorf Life [Dorf_Life],
    PKs Rebalancing [PK_REBALANCE],
    More Locations [more_locations],
    Tekitou Map Commercial Overhaul [tekitoumap],
    NPC Recruitment Options [recruitment_options],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More Survivor Stuff [more_survivor_stuff],
    Hydroponics [hydroponics],
    Food Irradiator [food_irradiator],
    Even More Mutations [even_more_mutations],
    Diluted Mutagens [diluted_mutagens],
    CDDA Variety Pack [ks_variety_pack],
    Cataclysm++ [Cata++],
    Youkai Enemies [Youkai_Disco],
    World on Fire [World_on_fire],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Salvaged Robots [Salvaged_Robots],
    PRM++ Patch [noctpk],
    No Hope [no_hope],
    Mutant Insects [mutant_insects],
    Mutant Animals [mutant_animals],
    Draco's Pig Mod [DracoPigMod],
    Draco's Dog Mod [DracoDogMod],
    DinoMod [DinoMod],
    Crazy Labs [crazy_labs],
    Compatible Add Bandits [GOV_BANDITS],
    Thermal Electric UPS [thermal_ups],
    The Vermilion Mod [VermilionMod],
    The Glory Of Cereal! [CerealMod],
    The Cool Mod [cool_mod],
    Soy mod [Soy mod],
    Rivtech Beam Swords [beamswordmod],
    Ricky's Future Armory [futurearmory],
    Project APEX [apex],
    Mythological Replicas [nw_pack],
    MST Extra [MST_Extra],
    No name () [],
    MOD to grow tea leaves [More tea leaf],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Makeshift Items Mod [makeshift],
    Large capacity storage CBMs [eps_cbm],
    Icecoon's Arsenal [ew_pack],
    Shinigami [reapermod],
    Ninja_Mod [Ninja]
]

![555555555](https://user-images.githubusercontent.com/43505148/104073656-b0e60980-5227-11eb-8bee-6752d8bd29a2.png)

No crashes, everything works as intended, thus, I will close this issue if you don't mind, since it's working correctly with all mods from the Modpack :-)

**Closed by Kenan2000** 2021-01-08 23:07 UTC

**Comment by slowleakage** [comment] 2021-01-08 23:47
I was just coming on to say that I believe it was an issue with the game being corrupted. I was unable to load the game the next day. Wipe and fresh install became necessary.  Thanks though for everything.  Now I must slay.
