### ISSUE TITLE
PKs_Rebalancing crashing the game and more errors

### ISSUE THREAD

**Issue by kegy21** [Kenan2000/CDDA-Kenan-Modpack#133] opened 2021-07-12 09:43 UTC
for some reason pk crashed my game i don't know what caused it to crash maybe it has something to do with me on android also more errors have appeared, i'm on a recent experimental version it but here's my debug log
[debug.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6800300/debug.log)

**Comment by Kenan2000** [comment] 2021-07-12 16:03
@kegy21 Most of errors that you've shown I've fixed, not sure how to fix PK rebalancing, have no idea what this problem is about, maybe @Theawesomeboophis or @meelock would be able to assist with testing it to understand what this error is about, how we can fix it hopefully as well

**Comment by Theawesomeboophis** [comment] 2021-07-12 16:22
I'll look into it, but I'm not available until weekend though.

**Comment by Theawesomeboophis** [comment] 2021-07-12 16:23
@kegy21 is an error message happening or does it just crash?

**Comment by Theawesomeboophis** [comment] 2021-07-12 16:33
Upon first glance it seems a problem with magazines crashed the game.

**Comment by Danny-San** [comment] 2021-07-12 17:41
I also have the same problem, the game crashes when I load the world, it stops in the recipes, 
I removed this mod and managed to load the world again, The problem is that it's hard to find the error as it just crashes, with no error message, I hope you guys can fix it.

**Comment by EPIC2X** [comment] 2021-07-12 18:57
This was the problem i was having after reinstalling and fixing the secronom error from a few days ago, the CTD was happening when finalizing the world and it reached the crafting recipes part, and the problem came back (iv been meaning to report it myself but haven't had the time) (also while enabling mods 1 at a time i figured out that PKs rebalance was 1 of the offending mods but at least 1 other mod is also causing trouble)

**Comment by kegy21** [comment] 2021-07-13 00:54
> @kegy21 is an error message happening or does it just crash?
it just crashes and just like danny said it also stops at recipe.

**Comment by Kenan2000** [comment] 2021-07-19 06:53
This has been fixed in latest update

**Closed by Kenan2000** 2021-07-19 06:53 UTC
